import Head from 'next/head';
import Image from 'next/image';
import { Text, Heading, Flex, Stack, Box } from '@chakra-ui/react';
import { ListItem, UnorderedList } from '@chakra-ui/react'
import { Radio, RadioGroup } from '@chakra-ui/react'
import { FormControl, FormLabel, Input, Textarea } from '@chakra-ui/react'
import { Button } from '@chakra-ui/react'
import { useColorMode, useColorModeValue } from '@chakra-ui/react'
import DarkMode from '../src/components/DarkMode'
import Logo from '../src/assets/logo/plotly-logo.svg';
import Darklogo from '../src/assets/logo/plotly-dark-logo.svg';
import Purple from '../src/assets/images/purple-image.svg';
import Colgate from '../src/assets/logo/colgate-logo.svg';
import Nvidia from '../src/assets/logo/nvidia-logo.svg';
import Kc from '../src/assets/logo/kc-logo.svg';
import Azz from '../src/assets/logo/azz-logo.svg';
import Tmobile from '../src/assets/logo/Tmobile-logo.svg';
import Tva from '../src/assets/logo/tva-logo.svg';

function Home() {

  const bgColor = useColorModeValue('white', '#1e1e1e')
  const secondaryTextColor = useColorModeValue('#1e1e1e', 'white')

  // Created the responsive design so that tablet falls under mobile from mockup
  const breakpoints = {
    base: '0em',
    sm: '30em',
    md: '48em',
    lg: '62em',
    xl: '80em',
  }

  return (
    <Stack boxSizing='border-box' p='0 1rem' bg={bgColor} m={{ xl: 'auto' }} >
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Plotly</title>
      </Head>
      <Box p={{ base: '4rem 2rem 0', xl: '4rem 5rem 5rem ' }} m={{ xl: 'auto' }}>
        <Flex as="header" flexDirection="row" justify="space-between" mb='1rem'
          width='100%'>
          <Image src={Logo} alt="plotly-logo" width='120px' />
          {/* <Image src={Darklogo} alt="plotly-logo" width='100px' /> */}
          <DarkMode />
        </Flex>


        <Box m={{ xl: '1rem' }} display={{ xl: 'block' }} >
          <Flex flexDirection='column' width={{ xl: '550px' }} pt={{ xl: '3rem' }}>
            <Flex as="main" flexDirection="column" p='0.8rem 0 0'>
              <Heading as='h1' size={{ base: 'xl', xl: '2xl' }} pb={{ xl: '1rem' }}>See Dash in action.</Heading>
              <Text fontSize={{ base: 'md', xl: '2xl' }} fontWeight='bold' mb='1rem'>Thank you for your interest in Dash Enterprise. We'll be in touch soon to schedule a demo.</Text>
            </Flex>
            <UnorderedList fontSize={{ base: 'sm', xl: 'md' }} colorScheme='#7A76FF;' color='#7E8489;'>
              <ListItem pb={{ base: '0.5rem', xl: '1rem' }} >Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</ListItem>
              <ListItem pb={{ base: '0.5rem', xl: '1rem' }}>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</ListItem>
              <ListItem >Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</ListItem>
            </UnorderedList>
          </Flex>
          <Box m={{ base: 'auto', xl: '0' }} p='3.2rem 1.5rem 2rem' borderRadius='1.4rem' b='0.5px solid  #ececec;' boxShadow='4px 8px 18px 0px #D9D9D940;' maxWidth={{ base: '40rem', xl: '30rem' }} zIndex='9999' position='relative' top={{ base: '1rem', sm: '1.8rem', md: '2.7rem', xl: '-23rem' }} left={{ xl: '38rem' }} bg={bgColor} >
            <RadioGroup defaultValue='1' >
              <Stack direction='row' spacing={{ base: 7, xl: 8 }} fontSize='xs' fontWeight='bold' mb='2rem'  >
                <Radio colorScheme='#7A76FF;' color={secondaryTextColor} value='1'>Professional</Radio>
                <Radio colorScheme='#7A76FF;' color={secondaryTextColor} value='2'>Student</Radio>
              </Stack>
            </RadioGroup>
            <FormControl color='#7E8489;'>
              <Flex flexDirection={{ base: 'column', xl: 'row' }}>
                <Flex flexDirection='column' mr={{ xl: '1rem' }}>
                  <FormLabel fontWeight='400' requiredIndicator>First name*</FormLabel>
                  <Input type='text' mb='1.5rem' />
                </Flex>
                <Flex flexDirection='column'>
                  < FormLabel fontWeight='400' requiredIndicator> Last name*</FormLabel>
                  <Input type='text' mb='1.5rem' />
                </Flex>
              </Flex>
              <Flex flexDirection={{ base: 'column', xl: 'row' }}>
                <Flex flexDirection='column' mr={{ xl: '1rem' }}>
                  <FormLabel fontWeight='400' requiredIndicator>Business Email*</FormLabel>
                  <Input type='email' mb='1.5rem' />
                </Flex>
                <Flex flexDirection='column'>
                  <FormLabel fontWeight='400' requiredIndicator>Phone*</FormLabel>
                  <Input type='tel' mb='1.5rem' />
                </Flex>
              </Flex>
              <Flex flexDirection={{ base: 'column', xl: 'row' }}>
                <Flex flexDirection='column' mr={{ xl: '1rem' }}>
                  <FormLabel fontWeight='400' requiredIndicator>Company Name*</FormLabel>
                  <Input type='text' mb='1.5rem' />
                </Flex>
                <Flex flexDirection='column'>
                  <FormLabel fontWeight='400' requiredIndicator>Title*</FormLabel>
                  <Input type='text' mb='1.5rem' />
                </Flex>
              </Flex>
              <FormLabel fontWeight='400' requiredIndicator>Tell us about your project*</FormLabel>
              <Textarea height={'8rem'} resize='none' mb='1.5rem' />
            </FormControl>
            <Flex flexDirection="row">
              <Button color='white' textTransform='uppercase' bgColor='#7A76FF;' mr='2rem' letterSpacing='0.15em' fontWeight='bold' p='1.5rem'>Send</Button>
              <Text pt='0.8rem' color='#7E8489;' fontSize='sm'>*required</Text>
            </Flex>
          </Box>
        </Box>

        <Flex flexDirection={{ base: 'column', xl: 'row' }} position={{ xl: 'relative' }} bottom={{ xl: '40rem' }} >
          <Box m={{ base: 'auto', xl: '0' }} mr={{ xl: '1rem' }}>
            <Image src={Purple} alt="purple-picture" maxWidth='100px' />
          </Box>
          <Flex display='flex' flexDirection='column' p={{ base: '2rem 4rem 6rem', xl: '6rem 0 0 ' }} mt={{ xl: '12rem' }}>
            <Flex mb='2rem' justify='space-between'>
              <Image src={Colgate} alt="colgate-logo" minWidth='100px' maxWidth='150px' />
              <Image src={Nvidia} alt="nvidia-logo" minWidth='100px' maxWidth='150px' />
              <Image src={Kc} alt="kc-logo" minWidth='100px' maxWidth='150px' />
            </Flex>
            <Flex justify='space-between' >
              <Image src={Azz} alt="azz-logo" minWidth='100px' maxWidth='150px' />
              <Image src={Tmobile} alt="Tmobile-logo" minWidth='100px' maxWidth='150px' />
              <Image src={Tva} alt="Tva-logo" minWidth='100px' maxWidth='150px' />
            </Flex>
          </Flex>
        </Flex>

      </Box>


    </Stack >
  )
}

export default Home;